""" 
█▀▀ █▀▀ █▄░█ █▀▀ █▀ █ █▀   █░░ █▀▀ █▀ █▀ █▀█ █▄░█ █▀   █░█ █▀█ █░░ ░ ▄█
█▄█ ██▄ █░▀█ ██▄ ▄█ █ ▄█   █▄▄ ██▄ ▄█ ▄█ █▄█ █░▀█ ▄█   ▀▄▀ █▄█ █▄▄ ▄ ░█ 
Welcome to the genesis gir lesson tutorials Volume 1! We start of the lessons with
you getting to know me! This program tells you more about me and who I am and is more like 
a cool story line about me make sure to pay attention to the functions used and the variables
how they are approached. Thanks for downloading~ 
⼕ㄖᗪ🝗ᗪ & 山尺讠セセ🝗𝓝 ⻏丫 Ꮆ🝗𝓝🝗丂讠丂 Ꮆ讠尺
"""
#This program takes you on a date with a girl cyborg threw a vast city!
print('-you open your eyes and its morning time it reads 8:00am-')
print('(press ENTER to read)')
input()
print('-while looking at  your clock you notice your late for your date-')
print('(press ENTER to read)')
input()
print('-your clock on your watch stops as you look at it and a bright flash happens-')
print('(press ENTER to read)')
input()
print('-A woman with a cyber robotic body appears in your room!-')
print('(press ENTER to read)')
input()
print('Kim the Robot™️: WOAH!')
print('(press ENTER!)')
input()
print('Kim the Robot™️: Who the hell are you?')
print()
print('-She looks at you up and down with a confused look-')
print('(Enter your name)')
name=input()
print()
print('Kim the Robot™️:Well fuck '+name+' Do you just summon women without their permission?')
print(' Press ENTER..')
input()
print('Kim the Robot™️:Thats kinda rude dont chu think!!?')
print('(Respond to her!)')
response=input()
print('Kim the Robot™️:... anyways')
print('Kim the Robot™️:I was at my house having a good day until you did')
print('this! Well you better make it up to me some how i hope?')
print('(Press ENTER..)')
input()
print('Kim the Robot™️:you know i always wanted to go on a date with a human!')
print('Kim the Robot™️: and you are kinda . .  cute looking.')
print('(Press ENTER to read)')
input()
print('(you notice her getting attracted to your presence')
print('(Press ENTER. .)')
input()        
print('(Kim the Robot™️:*Blinks softly*)')
print('(Press ENTER. .)')
input()
print('Kim the Robot™️:*gets closer and looks up at you*')
print('Kim the Robot™️: Hey man take me out somewhere.')
print('(Press Enter to Exit the room with her!)')
input()
print('(The mechanical door swooshes open!)')
print('(Press ENTER..)')
input()
print('Narrarator: And so began a great adventure and '+name+' and Kim™️ went on their way')
print('to their date in the cyber city with green mountains and metallic terrain and floating')
print('vehicals swooshing by and a busy street of villagers all walking to their jobs.')
print('(Press ENTER to continue!)')
input()
print('▄▀█   █░░ █▀█ █░█ █▀▀ █░░ █▄█   █▀▄ ▄▀█ ▀█▀ █▀▀')
print('█▀█   █▄▄ █▄█ ▀▄▀ ██▄ █▄▄ ░█░   █▄▀ █▀█ ░█░ ██▄™️')
print()
print('Kim the Robot™️: This city has been here for years if not decades and is historical')
print('i dont know what you did but i was in a different place. .  but now im here with you')
print('(Press ENTER to read)')
input()
print('Kim the Robot™️:We should go check out the rock villager mayor he will be waiting for us.')
print('(Walk to the Rock Villagers home Press ENTER..)')
input()
print('Game Sys Nofication: Go to the Mayors Sage home.')
print('(Press ENTER to accept the task)')
input()
print('Kim the Robot™️:Well lets go what are you waiting for?! Humans ugh lazy')
print('(Press ENTER to start walking)')
input()
print('*You start running doing parkour over boxes and crates over the city and come to')
print('the ally way you must double jump off the walls to get on the cities rooftops!')
print('(Press Enter to Wall Jump! 6 times should do it.)')
input()
print( name+' *𝙬𝙖𝙡𝙡 𝙟𝙪𝙢𝙥𝙨*')
print('(Press ENTER to wall Jump!)')
input()
print( name+' *𝙬𝙖𝙡𝙡 𝙟𝙪𝙢𝙥𝙨*')
print('(Press ENTER to wall Jump!)')
input()
print( name+' *𝙬𝙖𝙡𝙡 𝙟𝙪𝙢𝙥𝙨*')
print('(Press ENTER to wall Jump!)')
input()
print( name+' *𝙬𝙖𝙡𝙡 𝙟𝙪𝙢𝙥𝙨*')
print('(Press ENTER to wall Jump!)')
input()
print( name+' *𝙬𝙖𝙡𝙡 𝙟𝙪𝙢𝙥𝙨*')
print('(Press ENTER to wall Jump!)')
input()
print( name+' *𝙬𝙖𝙡𝙡 𝙟𝙪𝙢𝙥𝙨*')
print('Press ENTER..')
input()
print(name+' makes it ontop of the huge building having a vast view of the cyber city!')
print('(Press ENTER to continue)')
input()
print('Kim the Robot™️: Finally. ive been up here for like..')
print('(Press ENTER..')
input()
print('Kim the Robot™️:1 hour , humans are just so..lazy')
print('*Kim the Robot™️ looks over at you and blushes at the effort you have made*')
print('Press ENTER to read..')
input()
print('Kim the Robot™️: just cause.. you know how to wall..jump doesnt mean anything.')
print('Kim the Robot™️:i know plenty who do the same in their sleep . .  .')
print('(Press ENTER to read)')
input()

